apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foobarbaz
  name: foobarbaz
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: foobarbaz
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: foobarbaz
    spec:
      containers:
      - env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: foobarbaz-config
        image: eu.gcr.io/GOOGLE_CLOUD_PROJECT/foo-bar-baz:COMMIT_SHA
        imagePullPolicy: IfNotPresent
        name: foo-bar-baz-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30